sonar.projectKey=damoklesh_projet9
sonar.organization=damoklesh
sonar.sourceEncoding=UTF-8

sonar.sources=back/src/main,front/src
sonar.tests=back/src/test,front/src
sonar.test.inclusions=back/src/test/**/*.java,front/**/*.spec.ts

sonar.java.binaries=back/build/classes/java/main
sonar.java.test.binaries=back/build/classes/java/test
sonar.coverage.jacoco.xmlReportPaths=back/build/reports/jacoco/test/jacocoTestReport.xml
sonar.javascript.lcov.reportPaths=front/coverage/microcrm/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/.angular/**,**/*.spec.ts
sonar.coverage.exclusions=**/*.spec.ts,**/main.ts,**/config.ts

sonar.qualitygate.wait=true
