input {
  tcp {
    port => 5000
    codec => json_lines
    add_tag => ["backend"]
    add_field => { "log_type" => "application" }
  }

  file {
    path => "/var/log/caddy/access.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
    add_field => { "service" => "microcrm-frontend" }
    add_field => { "environment" => "docker" }
    add_field => { "log_type" => "http" }
    add_tag => ["frontend", "caddy"]
  }
}

filter {
  if "caddy" in [tags] and [ts] {
    date {
      match => ["ts", "UNIX"]
      target => "@timestamp"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "microcrm-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
